title: Modern Floorplan
views:
  - title: My Modern Floorplan
    path: floorplan
    theme: Google Dark Theme
    panel: true
    type: panel
    badges: []
    cards:
      - config:
          console_log_level: info
          defaults:
            hover_action: hover-info
            tap_action: more-info
          image: /local/floorplan/home_modern/home_modern.svg
          rules:
            - element: light-restroom-primary
              entity: light.hue3_light
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: light-bedroom-primary
              entity: light.hue2_light
              state_action:
                action: call-service
                service: floorplan.style_set
                service_data:
                  style: |
                    > if(entity.state === "on"){
                        console.log("Bob",entity);
                        return `fill:pink;`;
                      }else if(entity.state === "off"){
                        console.log("Not",entity);
                        return `fill:purple;`;
                      }
              double_tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: button.reload
              tap_action:
                action: fire-dom-event
                browser_mod:
                  service: browser_mod.javascript
                  data:
                    code: lovelace_reload();
            - element: button-music-text
              entity: media_player.kontor
              state_action:
                action: call-service
                service: floorplan.text_set
                service_data: |
                  > console.log(entity);
                  return `Music is currently ${entity.state}`
            - element: button-music-icon
              entity: media_player.kontor
              double_tap_action: false
              tap_action: false
              hold_action: more-info
            - element: light-livingroom-primary
              state_action:
                - action: call-service
                  service: floorplan.class_set
                  service_data: entity-state-${entity.state}
                - action: call-service
                  service: floorplan.dataset_set
                  service_data:
                    key: rgbcolor
                    value: ${entity.attributes.rgb_color}
                - action: null
                  service: floorplan.style_set
                  service_data:
                    style: >
                      > rgbColor = entity && entity.attributes &&
                      entity.attributes.rgb_color ? entity.attributes.rgb_color
                      : false; return rgbColor ?
                      `--livingroom-rgb-color:rgb(${rgbColor});`: '';
              hover_info_filter:
                - friendly_name
                - rgb_color
                - color_temp
                - brightness
              entity: light.hue1_light
              hold_action: more-info
              double_tap_action:
                - action: call-service
                  service: floorplan.execute
                  service_data:
                    test01: |
                      > console.log("Execute debug info", config, hass);
          stylesheet: /local/floorplan/home_modern/home_modern.css
        full_height: true
        type: custom:floorplan-card
